apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - configmap.yaml
  - customresourcedefinition.yaml
  - deployment.yaml
  - networkpolicy.yaml
  - role.yaml
  - rolebinding.yaml
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml
  - statefulset.yaml
