apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: metrics
    name: jaeger-operator
  name: jaeger-operator-metrics
  namespace: observability
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    name: jaeger-operator
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: jaeger-operator
  name: jaeger-operator-webhook-service
  namespace: observability
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    name: jaeger-operator
