---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-argocd-secret
  namespace: argocd
spec:
  encryptedData:
    oidc.keycloak.clientSecret: AgC9oOchKYJwJz7t7wWblbq1kYkKcvnO2BkqQNTn3otjJugtuyPdHv5pF3u+3ueZMIPMEfBI0XpNJ1lXnC4sFsacHp9jKbaBi3KXAEadvDGE1UWVPmig7PyWlJ7lkMZNEaMNDm9zz/7ANU89RzbrgBFyTzz5ucLmgoPP7gPj5TF8PwFu2OLgWt3/Q9iCh3IvIJwmkp3LalwcA/mBghM9mqNFEqllfTQKiC9PqZxTOMboRlcfNkAYd4tkm2GhJDQAq+SfKua7gwVp2uY/+L5xk1leAD4uj2SKTAOtZaQocIrb4Udv8jXfrllRZq3EYSi8gpz0q9T+rmq5ntEBtQ8wVtq6Fvd0WEF+OLroPAyU7XZSaYSVrfEzzCvon4i9yngmWFk3NWpn2/GBLdIBzLRVI3Rv0jNuurmah9WXQbkdZ5mGfUMh6NsU1gYGc6XJCqhZjUDEH9LhfXmCwfkHoV5wMCoav/pclQfATRdFwRqJ0BrxAmfdrdTV+GOwHG+DGN4p/vDKywxiJGyQs6HRC6vEyCRwSfpJ5YxA17E3duq0UE8pDpq1zgPpRL74uId5x0/1RQw8Y5mdkfpp5xoENldMPbcNcVOCefaUpIMl0wLiaAEEA5CvyGawwPS4eJkiGFwVh4IeC9KnnWUVc16rdr3eECKYy4fqWbfS77JaWGuLgoLHmJJ31Y3YI0nTdBlg+YECpB5CQDnOLawSD5QnQV5/gRqiPg==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/part-of: argocd
      name: keycloak-argocd-secret
      namespace: argocd
