- op: replace #action
  path: "/spec/template/spec/affinity/nodeAffinity" #resouirce we want to change
  value:       #value we want to use for patching
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/worker
              operator: In
              values:
                - 'true'
