apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-role-mapping-config
  namespace: observability
data:
  jaeger-role-mapping.json: |
    {
      "roles": [ "jaeger_role" ],
      "enabled": true,
      "rules": { "field": { "username": "jaeger_user" } }
    }

# POST /_security/role_mapping/jaeger_role_mapping