---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jaeger-user-secret
  namespace: observability
spec:
  encryptedData:
    jaeger_user: AgB50O4SzyJcYI1en6KXERY2DLtovkfUG+Ji8kJDNUvq7g72P+5jBEcWazJlNDElDtivZ/IlwPv1EkrbtvIM1aHOvDO8yPYMn5TcCqm5y8pWp/1fCTY8OEHZK547mg3kQ8n3YYztSNBhCZ8ItJQgEsNLn2ybJ5q6mJLIYJx1t2u+31Bj2r/Aq1A/vXFFDGl2/HvLzwmVR/0JGOq0Ok3rLTAtF1VxeZnXdXsd/ZJEgmQK3LPbn3J9QQFz/Q3fYFwJOAyS6Xgh5ifSNFNJzIv1uLvo1USiaUVDce75FV6o1jxS6Rpy1VUEmwZRi5yTVWztoxZiRyyyBSfzdyBiUn4VWJkKoej4mwp2dGWGXRxhK2MCqvgRSx0MxtW8q2DN77wzNr/qO1Lr5pw33nctrZVYx3OmEOrqe5l+KkfLo7Suyqp6uTJdrRscRyCZt3Mulg+M/grt1S+mGn9tNJgAPvk6jk8qWdt9seI+++CCe3lhfaKD8QM8cF5XYqtNnhkvSRCmtg8LgFKXDg30AGLqtrCjLxgGzmcaNFsI+7IelyTHP8L8kJfsMTdhrD77gYynGsfP5AKcSburEwdciIco2NAbnZPPRwQOx4ohGUyP+8p8hcXF+r0yjXyI6bAkv0EBdVml2ZDxmyY7cJy17qrpWDPeMmau+wZC64K7FcS0Srmo00QCYBGVUS+NEr18x6yl40Sv/NMp93dMLEfmgFrE5gs=
  template:
    metadata:
      creationTimestamp: null
      labels:
        common.k8s.elastic.co/type: elasticsearch
        eck.k8s.elastic.co/credentials: "true"
        eck.k8s.elastic.co/owner-kind: Elasticsearch
        eck.k8s.elastic.co/owner-name: jaeger-elasticsearch
        eck.k8s.elastic.co/owner-namespace: observability
        elasticsearch.k8s.elastic.co/cluster-name: jaeger-elasticsearch
      name: jaeger-user-secret
      namespace: observability
    type: Opaque
