apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  url: https://k8s-test.internal/apps/argocd/
  oidc.config: |
    name: Keycloak
    issuer: https://sso.internal/realms/internal
    clientID: argocd-sso-client
    clientSecret: $oidc.keycloak.clientSecret
    requestedScopes: ["openid", "profile", "email", "roles", "web-origins"]