apiVersion: v1
kind: Secret
metadata:
  name: k8s-argo-apps-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://bitbucket.org/my-org/k8s-argo-apps/src/main
---
apiVersion: v1
kind: Secret
metadata:
  name: k8s-infra-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://bitbucket.org/my-org/k8s-infra/src/main
---
apiVersion: v1
kind: Secret
metadata:
  name: bitbucket-my-org-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: https://bitbucket.org/my-org
  username: my-username
  password: my-password