apiVersion: v1
kind: Secret
metadata:
  name: keycloak-argocd-secret
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
data:
  oidc.keycloak.clientSecret: base64_encoded_sso_client_secret
