apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability

resources:
- ../../base/v1.57.0

patches:
- path: jaeger-operator-patch.yaml
  target:
    kind: Deployment
    name: jaeger-operator
    namespace: observability