apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - customresourcedefinition.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - configmap.yaml
  - namespace.yaml
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml
  - statefulset.yaml
  - validatingwebhookconfiguration.yaml
