apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/version: 2.13.0
    control-plane: elastic-operator
  name: elastic-operator
  namespace: elastic-system
